title: "Tomer Landsberger"
description: "Founder | Scientist | Transhumanist | Vitalist | BioTech | MedTech | DeSci"
baseurl: ""                       # keep empty unless the site lives in a sub-folder
url: "https://tomerlan.github.io"

# --- site settings ---
taglong: "NOT going gentle into the good night"   # style line stays
logo: "/assets/files/og-image.jpg"                 # 1200×630 social preview; adjust path if needed
photo: "assets/files/avatar.png"                 # head-shot used by theme

# --- author ---
author:
  name: "Tomer Landsberger"
  email: "tomer.landsberger@gmail.com"

# --- social links ---
social:
  github: tomerlan
  wordpress: alsoofthetreeoflife
  google_scholar: "citations?user=wswTSOoAAAAJ&hl=en"
  linkedin: tomer-landsberger-48127393
  substack: tomerlan
  x: tomerlan87
  sciborg: "https://www.sciborg.xyz/"

# --- build settings ---
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
  - archive                    # merged all excludes into one list

plugins:
  - jekyll-seo-tag             # generates meta / OG / JSON-LD
  - jekyll-sitemap             # auto-creates /sitemap.xml each build

# --- analytics ---
google_analytics: "G-DMHRV5LZQL"   # GitHub Pages injects GA script automatically
